MODEL:
  intent_model: "checkpoints/intent-model-thai/TF_multioutput_linear_regress.pkl"
  answer_model: "checkpoints/simcse-model-thai-version-supAIkeyword"
  conf_threshold: 0.5
CUSTOM_DICT:
  words: ["เงินสนับสนุน", "เงินทุน", "ได้รับเงิน", "ได้รับทุน","ได้รับเงินทุน" ,"ได้ตังค์" ,"ได้เงิน" ,"รางวัล" ,"สิทธิประโยชน์" ,"เงินเดือน","เงินในแต่ละช่วง","โครงการ", "กี่ระดับ", "กี่เลเวล", "รูปแบบ", "รูปแบบโครงการ", "รูปแบบโครงการ",
  "ขั้นตอน", "การสมัคร", "สมัครอย่างไร", "ร่วมโครงการ", "ลงทะเบียน", "เสียเงิน", "เสียตังค์", "่จ่ายเงิน", "ค่าใช้จ่าย", "เกณฑ์คัดเลือก", "เกณฑ์การประเมิน", "คัดเลือก", "โอนหน่วยกิต", "เทียบโอน", "สหกิจ", "เอไอ", "หลักสูตร", "หลักสูตรเอไอระดับพื้นฐาน",
  "Fundamental level", "เลเวล1", "level1", "lv1", "lv.1", "lvl1", "เลเวล2", "level2", "lv2", "lv.2", "lvl2", "เลเวล3", "level3", "lv3", "lv.3", "lvl3", "หลักสูตรเอไอระดับกลาง", "เอไอระดับกลาง", "Intermediate level",
  "หลักสูตรเอไอขั้นสูง", "Applied level", "เอไอระดับสูง", "การศึกษา", "นักศึกษา","บอท", "bot"]
DATA_CORPUS:
  data_csv: "/Projects/configs/data_corpus_v2.csv"

DATA_VERSION:
  file_path: "https://drive.google.com/drive/folders/12OAqAU0tI_qu-vqLD_elvmLJ0fP0ONB5?usp=sharing"

KEYWORD_INTENT:
  aiforall: ["AI"]
  superaiคือ: ["Dummy here"]
  ขั้นตอนในการสมัคร: ["ขั้นตอน", "สมัคร", "การสมัคร", "เข้าร่วม", "ลงทะเบียน"]
  ค่าใช้จ่ายในการสมัคร: ["ค่าใช้จ่าย", "เสียค่าใช้จ่าย", "จ่าย", "เสียเงิน", "ค่าสมัคร", "รายจ่าย"]
  จำนวนผู้สมัคร: ["จำนวน", "ผู้สมัคร", "จำกัด", "รับ", "เยอะ"]
  ติดต่อผู้ดูแล: ["ติดต่อ", "ผู้ดูแล", "การคุย", "line", "facebook", "live", "chat", "ผู้ประสานงาน", "แอดมิน", "คน"]
  ทักทาย: ["สวัสดี", "Hi", "Hello", "Hey"]
  ภาพรวมโครงการ: ["ภาพรวม", "เมื่อก่อน", "ที่ผ่านมา"]
  รูปแบบโครงการ: ["กิจกรรม", "ระดับ", "รูปแบบ", "โครงการ", "แบ่งออก"]
  หน้าที่ของบอท: ["Dummy here"]
  หลักสูตรเอไอขั้นสูง: ["ขั้นสูง", "3", "applied"]
  หลักสูตรเอไอระดับกลาง: ["กลาง", "2" ,"intermediate"]
  หลักสูตรเอไอระดับพื้นฐาน: ["พื้นฐาน", "1", "fundamental"]
  เกณฑ์ในการคัดเลือก: ["เกณฑ์", "การประเมิน", "การคัดเลือก", "คัดเลือก", "การคัดเลือก", "ผ่าน", "คะแนน"]
  เงินสนับสนุน: [Dummy here"]
  เทียบโอนหน่วยกิต: ["เทียบ", "โอน", "หน่วยกิต", "สห", "กิจ" ]
  เอกสารในการสมัคร: ["เอกสาร", "หนังสือ"]
  