MODEL:
  intent_model: "checkpoints/intent-model-thai/TF_multioutput_linear_regress.pkl"
  answer_model: "checkpoints/simcse-model-thai-version-supAIkeyword"

CUSTOM_DICT:
  words: ["สวัสดีครับ", "สวัสดี", "ว่าไง", "ดีครับ", "ดีค่ะ", "Hello", "โย่ว", "เป็นไงบ้าง", "ทักทาย", "โหลๆ", "เปิดรับ", # -> ทักทาย
  "ขั้นตอน", "การสมัคร", "สมัคร", "เข้าร่วม", "ลงทะเบียน", # -> ขั้นตอนในการสมัคร
  "เสียเงิน", "เสียตังค์", "ค่าใช้จ่าย", "จ่าย", "รายจ่าย", "ค่าธรรมเนียม", # -> ค่าใช้จ่ายในการสมัคร
  "จำนวน", "กี่คน", "จำกัด", "ผู้สมัคร", "รับ", # -> จำนวนผู้สมัคร
  "เกณฑ์", "คัดเลือก", "เข้ารอบ", "อายุ", # -> เกณฑ์ในการคัดเลือก
  "ได้เงิน", "เงินสนับสนุน", "เงินเดือน", # -> เงินสนับสนุน
  "ไม่เข้าใจ", "ช่วยเหลือ", # -> ติดต่อผู้ดูแล
  "ภาพรวม", "บรรยากาศ", "Online", "Onsite", "ระยะเวลา" , "ทีผ่านมา", "กำหนดการ",  # ภาพรวมโครงการ
  "โครงการ", "รูปแบบ", "แบ่งออก", "เลเวล", "เรียน", "แบ่งเป็น", # รูปแบบโครงการ
  "ขั้นสูง", "3", "applied", "เลเวล3", "level3", "lv3", "lvl3", "ระดับสูง", "รอบ3", "รอบสาม", "รอบ 3", # หลักสูตรเอไอขั้นสูง
  "ขั้นกลาง", "2" ,"intermediate", "ขั้นสอง", "เลเวล2", "level2", "lv2", "lvl2", "กลาง", "รอบสอง", "รอบ 2", "รอบ2", # หลักสูตรเอไอระดับกลาง
  "พื้นฐาน", "1", "fundamental", "ขั้นแรก", "เลเวล1", "level1", "lv1", "lvl1","รอบหนึ่ง", "รอบ 1", "รอบ1", "รอบแรก",  # หลักสูตรเอไอเบื้องต้น
  "สหกิจ", "เทียบ", "โอน" , "เทียบโอน", "หน่วยกิจ", "หน่วยกิต", # เทียบโอนหน่วยกิต
  "เอกสาร", "หนังสือ", "ยื่น", # เอกสารในการสมัคร
  "รหัสประจำตัว", "รหัสผู้สมัคร", # รหัสประจำตัว
  "หลักสูตรการเรียน", "เนื้อหา", "อบรม", "ความรู้", "สกิล", # หลักสูตรการเรียน
  "ใบประกาศ", "ใบเซอร์", "ใบเซอ", "ใบcer", "certificate", # ใบประกาศ
  "สอบ", "แนวข้อสอบ", "ข้อสอบ", # แนวข้อสอบ
  "Hackathon", "แฮคคาธอน", "แฮคกาธอน", "แฮกกาธอน", "แข่งขัน", "ทีม", "แข่งขัน", # Hackathon
  ] 
DATA_CORPUS:
  data_csv: "/Projects/configs/data_corpus_v2.csv"
  keyword_csv: "/Projects/configs/keyword_intent.csv"

DATA_VERSION:
  file_path: "https://drive.google.com/drive/folders/12OAqAU0tI_qu-vqLD_elvmLJ0fP0ONB5?usp=sharing"

KEYWORD_INTENT:
  aiforall: ["DUMMY"]
  superaiคือ: ["AI", "ai", "Super AI", "season3"] #
  ขั้นตอนในการสมัคร: ["ขั้นตอน", "สมัคร", "การสมัคร", "เข้าร่วม", "ลงทะเบียน", "เข้าร่วม", "เปิดรับ"] # 
  ค่าใช้จ่ายในการสมัคร: ["ค่าใช้จ่าย", "เสียค่าใช้จ่าย", "จ่าย", "เสียเงิน", "รายจ่าย", "ค่าธรรมเนียม"] # 
  จำนวนผู้สมัคร: ["จำนวน", "ผู้สมัคร", "จำกัด", "รับ"] # 
  ติดต่อผู้ดูแล: ["ติดต่อ", "ผู้ดูแล", "การคุย", "line", "facebook", "live", "chat", "ผู้ประสานงาน", "แอดมิน", "ไม่เข้าใจ" , "ช่วยเหลือ"] #
  ทักทาย: ["สวัสดี", "Hi", "Hello", "Hey", "สวัสดีครับ", "ดีครับ", "ดีค่ะ", "เป็นไงบ้าง", "ทักทาย", "โหล"] # 
  ภาพรวมโครงการ: ["ภาพรวม", "ค่าย", "ที่ผ่านมา", "Online", "Onsite", "ระยะเวลา", "บรรยากาศ"] #
  รูปแบบโครงการ: ["กิจกรรม", "ระดับ", "รูปแบบ", "แบ่งออก", "เรียน", "แบ่งเป็น", "เลเวล"] #
  หน้าที่ของบอท: ["DUMMY"]
  หลักสูตรเอไอขั้นสูง: ["ขั้นสูง", "3", "applied", "ขั้นสาม" , "level3", "lv3", "lvl3"] #
  หลักสูตรเอไอระดับกลาง: ["ขั้นกลาง", "2" ,"intermediate", "ขั้นสอง", "level2", "lv2", "lvl2"] #
  หลักสูตรเอไอระดับพื้นฐาน: ["พื้นฐาน", "1", "fundamental", "ขั้นแรก", "level1", "lv1", "lvl1"] #
  เกณฑ์ในการคัดเลือก: ["เกณฑ์", "การประเมิน", "การคัดเลือก", "คัดเลือก", "การคัดเลือก", "ผ่าน", "คะแนน", "อายุ", "คุณสมบัติ" ,"ประเมิน", "ใคร"] #
  เงินสนับสนุน: ["เงินสนับสนุน", "ทุน" , "เงินเดือน", "รางวัล" , "ได้เงิน"] #
  เทียบโอนหน่วยกิต: ["เทียบ", "โอน", "หน่วยกิต", "หน่วยกิจ", "สหกิจ"] #
  เอกสารในการสมัคร: ["เอกสาร", "หนังสือ", "ยื่น"] #